let zm1 = 10;
let zm2 = "to jest napis";
let zm3 = "To jest napis " + 20;
let zm4 = "20" + 1;
let zm5 = "21" - 1;
let zm6 = "20a" - 1;
let zm7 = 10 - "5";
let zm8 = 10 + "a3";
let zm9 = 10 / 333;
let zm10;
let a, b, c;
a = 5;
b = 0;
c = a / b;
let liczba1 = 1;
let liczba2 = Infinity;
let wynik = liczba1 / liczba2;

console.log( "zm1: ", typeof zm1, "\t\t-> wynik = ", zm1 );
console.log( "zm2: ", typeof zm2, "\t\t-> wynik = ", zm2 );
console.log( "zm3: ", typeof zm3, "\t\t-> wynik = ", zm3 );
console.log( "zm4: ", typeof zm4, "\t\t-> wynik = ", zm4 );
console.log( "zm5: ", typeof zm5, "\t\t-> wynik = ", zm5 );
console.log( "zm6: ", typeof zm6, "\t\t-> wynik = ", zm6 );
console.log( "zm7: ", typeof zm7, "\t\t-> wynik = ", zm7 );
console.log( "zm8: ", typeof zm8, "\t\t-> wynik = ", zm8 );
console.log( "zm9: ", typeof zm9, "\t\t-> wynik = ", zm9 );
console.log( "zm10: ", typeof zm10, "\t-> wynik = ", zm10 );
console.log( "a: ", typeof a, "\t\t\t-> wynik = ", a );
console.log( "b: ", typeof b, "\t\t\t-> wynik = ", b );
console.log( "c: ", typeof c, "\t\t\t-> wynik = ", c );
console.log( "liczba1: ", typeof liczba1, "\t-> wynik = ", liczba1 );
console.log( "liczba2: ", typeof liczba2, "\t-> wynik = ", liczba2 );
console.log( "wynik: ", typeof wynik, "\t\t-> wynik = ", wynik );